import React from 'react';
import { useReports, useGenerateReport } from '../hooks/useReports';
import { PageHeader } from '../components/layout/PageHeader';
import { Table } from '../components/common/Table';
import type { Column } from '../components/common/Table';
import { Button } from '../components/forms/Button';
import type { ReportSummary } from '../types';
import { Download, FileText } from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const { data: reports, isLoading, isError, refetch } = useReports();
  const generateMutation = useGenerateReport();

  const columns: Column<ReportSummary>[] = [
    { key: 'title', header: 'Report Title', sortable: true, render: (r) => <span className="font-semibold text-slate-800 dark:text-slate-200">{r.title}</span> },
    { key: 'category', header: 'Module Category', sortable: true, render: (r) => <span className="text-xs font-mono bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-slate-600">{r.category}</span> },
    { key: 'generatedAt', header: 'Generated Timestamp', sortable: true },
    { key: 'generatedBy', header: 'Generated By' },
    { key: 'format', header: 'Format', render: (r) => <span className="font-mono text-xs font-bold text-[var(--color-secondary)]">{r.format}</span> },
    {
      key: 'actions',
      header: 'Actions',
      align: 'right',
      render: (r) => (
        <Button
          size="sm"
          variant="outline"
          onClick={() => alert(`Downloading ${r.title} (${r.format})`)}
          icon={<Download className="w-3.5 h-3.5 text-slate-500" />}
        >
          Download Report
        </Button>
      ),
    },
  ];

  const handleGenerate = () => {
    generateMutation.mutate({
      title: 'Global Semiconductor Fab Engineer Utilization Report',
      category: 'Utilization',
      format: 'PDF',
    });
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Enterprise Operational Reports & Analytics"
        subtitle="Export executive PDF summaries, CSV metrics, and Excel workbooks for field engineer utilization."
        actions={
          <Button
            loading={generateMutation.isPending}
            onClick={handleGenerate}
            icon={<FileText className="w-4 h-4" />}
          >
            Generate New Report
          </Button>
        }
      />

      <Table columns={columns} data={reports || []} isLoading={isLoading} isError={isError} onRetry={refetch} emptyTitle="No Reports Generated Yet" />
    </div>
  );
};
